name: 'Setup PNPM'

on:
  workflow_call:

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.53.6

      - name: Download deps
        run: pnpm i --frozen-lockfile

      - name: Package build
        run: pnpm build

      - name: Type check
        run: pnpm tsc

      - name: Run lint and format check
        run: pnpm check

      - name: Run knip
        run: pnpm knip
