name: 'Setup PNPM'

on:
  workflow_call:

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.53.6

      - name: Download deps
        run: pnpm i --frozen-lockfile

      - name: Package build
        run: pnpm build
      
      - name: Run biome check
        run: pnpm biome:check
