name: 'Setup PNPM'

on:
  workflow_call:

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.53.6

      - name: Download deps
        run: pnpm i --frozen-lockfile

      - name: Package build
        run: pnpm build

      - name: Type check
        run: pnpm tsc

      - name: Run lint and format check
        run: pnpm check

      - name: Run knip
        run: pnpm knip
